[package]
name = "yydb-wasm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Browser WebAssembly binding for YYDB"
readme = "readme.md"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
blake3 = { workspace = true }
serde_json = { workspace = true }
vos = { workspace = true }
yydb = { workspace = true }
wasm-bindgen = { workspace = true }
getrandom = { version = "0.4", features = ["wasm_js"] }

[dev-dependencies]
yydb = { workspace = true }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
