import { scalarToTs, type TsSchemaIr } from './ir.js';

const BANNER = '// @generated by `yydb generate`, do not edit!';

function quoteSingle(value: string): string {
    const escaped = value
        .replace(/\\/g, '\\\\')
        .replace(/'/g, "\\'")
        .replace(/\r/g, '\\r')
        .replace(/\n/g, '\\n')
        .replace(/\t/g, '\\t');
    return `'${escaped}'`;
}

/** Generate `schema.generated.ts` source from IR. */
export function emitTypeScript(ir: TsSchemaIr): string {
    const lines: string[] = [BANNER];
    lines.push(`export const APP_SCHEMA_VERSION = ${ir.schemaVersion};`);
    lines.push(`export const APP_SCHEMA = ${quoteSingle(ir.vosSource)};`);
    for (const table of ir.tables) {
        lines.push(emitInterfaceRow(table));
    }
    lines.push(emitInterfaceAppDb(ir));
    lines.push(`export type AppDbTableName = keyof AppDb['tables'];`);
    return `${lines.join('\n')}\n`;
}

function emitInterfaceRow(table: TsSchemaIr['tables'][number]): string {
    const lines = [`export interface ${table.name}Row {`];
    for (const field of table.fields) {
        lines.push(`    ${field.name}: ${scalarToTs(field.ty)};`);
    }
    lines.push('}');
    return lines.join('\n');
}

function emitInterfaceAppDb(ir: TsSchemaIr): string {
    const tableLines = ir.tables.map((table) => `        ${table.name}: ${table.name}Row;`);
    return ['export interface AppDb {', '    tables: {', ...tableLines, '    };', '}'].join('\n');
}
